### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [yummymell0w/jammming_feature_request#1]
Adding the ability to trigger the search function by pressing enter button will indeed make the app faster to navigate. The technical design you have layed out for the enter key is correct, following your instructions, I would have 
```
  handleEnter(event) {
    if(event.keyCode === 13) {
      this.search();
    }
}
```
and
`<input onKeyDown={this.handleEnter}/>`

**Comment by yummymell0w** [comment]
yep, this is correct result. Except you forgot to mention that you need to bind this method in the SearchBar constructor.
